name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main  # main 브랜치에 push 될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # GitHub Container Registry 로그인
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Docker 이미지 빌드 및 푸시
    - name: Build and Push Docker image
      run: |
        docker build -t ghcr.io/nextgeninsight/n8n-custom:latest .
        docker push ghcr.io/nextgeninsight/n8n-custom:latest

    # Azure 로그인
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Azure Web App 배포
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: n8n-koreaeu-com
        images: ghcr.io/nextgeninsight/n8n-custom:latest
