name: Build and Deploy to Azure Web App - n8n-koreaeu-com

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy container to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: n8n-koreaeu-com  # 정확한 Web App 리소스 이름
          slot-name: Production      # 기본 슬롯 (대소문자 중요하지 않지만 일관성 유지)
          images: ghcr.io/nextgeninsight/n8n-custom:latest
